name: Helm chart test workflow

on:
  push:
    branches:
      - '**'
    pull_request:
      branches: [main]
    paths:
      - "charts/universal-chart/**"
  schedule:
    - cron: "0 3 * * 5" # Every friday at 3 AM

jobs:
  test:
    name: test helm chart
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v2.1
      - name: helm lint
        run: helm lint charts/universal-chart
      - name: testsuite
        run: |
          cd charts/universal-chart
          ./testit.sh
